import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#c9e6ff",
        "outline-variant": "#4d4354",
        "surface-container-low": "#181b25",
        "on-tertiary-container": "#002d43",
        outline: "#988d9f",
        "on-secondary-fixed": "#002203",
        "on-primary-fixed": "#2c0051",
        "on-surface": "#dfe2ef",
        "on-primary-container": "#400071",
        error: "#ffb4ab",
        "secondary-container": "#13ff43",
        "on-tertiary-fixed-variant": "#004c6e",
        "inverse-primary": "#842bd2",
        "on-primary-fixed-variant": "#6900b3",
        "surface-dim": "#0f131c",
        "on-secondary": "#003907",
        background: "#0f131c",
        "primary-fixed": "#f0dbff",
        secondary: "#ecffe3",
        "on-secondary-fixed-variant": "#00530e",
        "on-secondary-container": "#007117",
        "on-background": "#dfe2ef",
        "on-surface-variant": "#cfc2d6",
        "surface-tint": "#ddb7ff",
        "on-tertiary": "#00334d",
        "error-container": "#93000a",
        "primary-container": "#b76dff",
        "tertiary-fixed-dim": "#89ceff",
        "primary-fixed-dim": "#ddb7ff",
        "inverse-on-surface": "#2c303a",
        "tertiary-container": "#009ada",
        primary: "#ddb7ff",
        "on-primary": "#490080",
        "on-error": "#690005",
        "surface-container": "#1c1f29",
        surface: "#0f131c",
        "on-error-container": "#ffdad6",
        "surface-bright": "#353943",
        tertiary: "#89ceff",
        "inverse-surface": "#dfe2ef",
        "secondary-fixed-dim": "#00e639",
        "surface-container-highest": "#31353f",
        "surface-container-high": "#262a34",
        "secondary-fixed": "#72ff70",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-lowest": "#0a0e17",
        "surface-variant": "#31353f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "max-width": "1280px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      fontFamily: {
        "headline-xl": ["Sora"],
        "body-md": ["JetBrains Mono"],
        "body-sm": ["JetBrains Mono"],
        "body-lg": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "headline-md": ["Sora"],
      },
      fontSize: {
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
